<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="convert-lunar.js" CopyToOutputDirectory="PreserveNewest" />
    <None Include="package.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="node_modules/**" CopyToOutputDirectory="PreserveNewest" Condition="Exists('node_modules')" />
  </ItemGroup>

</Project>
